services:
  - type: web
    name: ndt-l-flaw
    env: python
    region: singapore        # pick closest
    plan: free               # or starter
    buildCommand: >
      pip install --upgrade pip setuptools wheel &&
      pip install --no-cache-dir -r requirements.txt
    startCommand: >
      streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
      - key: STREAMLIT_SERVER_FILE_WATCHER_TYPE
        value: "none"
      - key: UPLOAD_DIR
        value: "/data/uploads"
      - key: MODEL_DIR
        value: "/data/models"
  
