services:
  - type: web
    name: ndt-ml-flaw
    env: python
    region: singapore    # or oregon/frankfurt; pick closest
    plan: free          # or starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
      - key: STREAMLIT_SERVER_FILE_WATCHER_TYPE
        value: "none"
      - key: UPLOAD_DIR
        value: "/data/uploads"
      - key: MODEL_DIR
        value: "/data/models"
   
